### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by neophilism** [ScriptProdigy/CryptsyPythonAPI#2]
Hello, 

I can't get the example usage found in README.md to work.  Is it up to date?

Thanks, Phil

**Comment by ScriptProdigy** [comment]
Hey Phil, can you describe the issue you're having? It should still work.
The API on Cryptsy hasn't changed much but a new function or two.

On Mon, Dec 9, 2013 at 2:26 PM, pgalinsky notifications@github.com wrote:

> Hello,
> 
> I can't get the example usage found in README.md to work. Is it up to date?
> 
> Thanks, Phil
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ScriptProdigy/CryptsyPythonAPI/issues/2
> .

## 

-- Matt Smith

**Comment by neophilism** [comment]
When I run the following code I get the error message that I've pasted below the code.  The only change that I made to the example found in README.md (other then entering my own key and secret) is to have the code wait for 60 seconds before canceling the order so I can manually check that the order was placed on cryptsy.com.  I haven't made any changes to the file Cryptsy.py and I've used a number of its other functions which are all are working correctly, this is the first error message that I've run into.

```
import Cryptsy
import time

Exchange = Cryptsy.Cryptsy('my key', 'my secret')
Exchange.createOrder(26, "Buy", 100, 0.00000001)       # Buy 100 dgc at .00000001 each
time.sleep(60)
Exchange.cancelMarketOrders(26)                        # Cancels all orders in market 26, dgc
```

Here's the error message:

Traceback (most recent call last):
  File "C:/Python27/cryptobot/purchase_test.py", line 5, in <module>
    Exchange.createOrder(26, "Buy", 100, 0.00000001)       # Buy 100 dgc at .00000001 each
  File "C:/Python27/cryptobot\Cryptsy.py", line 177, in createOrder
    return self.api_query('createorder', {'marketid': marketid, 'ordertype': ordertype, 'quantity': quantity, 'price': price})
  File "C:/Python27/cryptobot\Cryptsy.py", line 45, in api_query
    return self.post_process(jsonRet)
  File "C:/Python27/cryptobot\Cryptsy.py", line 19, in post_process
    if(isinstance(after['return'], list)):
KeyError: 'return'

**Comment by ScriptProdigy** [comment]
Looking into it right now. Ill also be updating the library likely tonight
with the latest functions on cryptsy. I'll get back to you asap, thanks for
the information!

On Mon, Dec 9, 2013 at 5:41 PM, pgalinsky notifications@github.com wrote:

> When I run the following code I get the error message that I've pasted
> below the code. The only change that I made to the example found in
> README.md (other then entering my own key and secret) is to have the code
> wait for 60 seconds before canceling the order so I can manually check that
> the order was placed on cryptsy.com. I haven't made any changes to the
> file Cryptsy.py and I've used a number of its other functions which are all
> are working correctly, this is the first error message that I've run into.
> 
> import Cryptsy
> import time
> 
> Exchange = Cryptsy.Cryptsy('my key', 'my secret')
> Exchange.createOrder(26, "Buy", 100, 0.00000001)       # Buy 100 dgc at .00000001 each
> time.sleep(60)
> Exchange.cancelMarketOrders(26)                        # Cancels all orders in market 26, dgc
> 
> Here's the error message:
> 
> Traceback (most recent call last):
> File "C:/Python27/cryptobot/purchase_test.py", line 5, in
> Exchange.createOrder(26, "Buy", 100, 0.00000001) # Buy 100 dgc at
> .00000001 each
> File "C:/Python27/cryptobot\Cryptsy.py", line 177, in createOrder
> return self.api_query('createorder', {'marketid': marketid, 'ordertype':
> ordertype, 'quantity': quantity, 'price': price})
> File "C:/Python27/cryptobot\Cryptsy.py", line 45, in api_query
> return self.post_process(jsonRet)
> File "C:/Python27/cryptobot\Cryptsy.py", line 19, in post_process
> if(isinstance(after['return'], list)):
> KeyError: 'return'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ScriptProdigy/CryptsyPythonAPI/issues/2#issuecomment-30181621
> .

## 

-- Matt Smith

**Comment by neophilism** [comment]
Great, thanks!

**Comment by ScriptProdigy** [comment]
Yep, duplicating the same issue, working on it now! Shouldn't be too long
for an update!

On Mon, Dec 9, 2013 at 5:51 PM, pgalinsky notifications@github.com wrote:

> Great, thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ScriptProdigy/CryptsyPythonAPI/issues/2#issuecomment-30182487
> .

## 

-- Matt Smith

**Comment by ScriptProdigy** [comment]
All better, working now! Will continue working on it to add latest stuff to it. Maybe adding some new features like ohlc data generation and such. We'll see what happens. :) Thanks for letting me know about the bug!

**Comment by ScriptProdigy** [comment]
Also.. Forgot to mention, print out the results of the functions to
determine errors in returns such as not making your buy order large enough
;)

On Mon, Dec 9, 2013 at 5:54 PM, Matt Smith matt.joseph.smith@gmail.comwrote:

> Yep, duplicating the same issue, working on it now! Shouldn't be too long
> for an update!
> 
> On Mon, Dec 9, 2013 at 5:51 PM, pgalinsky notifications@github.comwrote:
> 
> > Great, thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ScriptProdigy/CryptsyPythonAPI/issues/2#issuecomment-30182487
> > .
> 
> ## 
> 
> -- Matt Smith

## 

-- Matt Smith

**Comment by neophilism** [comment]
Will do, thanks for the tip!
