### ISSUE TITLE
Python 3.4 compatible fixes - compatibibly / errors

### ISSUE THREAD

**Issue by fogodlc** [ScriptProdigy/CryptsyPythonAPI#8]
import urllib.parse instead of urllib for python 3.4 compatibility

def _query(self, method, id=None, action=None, query=[], get_method="GET"):    #query needs to be []

changing query from {} to [] fixes one issue but  lands  in "sign="  with encoding error, add                 .encode(utf-8) to queryStr.

query.append(('nonce', time.time()))  
        queryStr = urllib.parse.urlencode(query)    #Python 3.4 only
...
...
        sign = hmac.new(self.PrivateKey.encode('utf-8'),  
                        queryStr.encode('utf-8'),              # added  " .encode('utf-8') "
                        hashlib.sha512).hexdigest()         #
        headers = {'Sign': sign, 'Key': self.PublicKey.encode('utf-8')}

Sorry if this is not formatted well. I have been writing python 1 week now. Those with real coding experience please correct, add, modify and improve. Obviously. I have made more progress in that one week than this project has in months now. Hope we can have WORKING DEMO (Python 2.7 or 3.4) soon!

**Comment by ScriptProdigy** [comment]
Hey dogodlc, appreciate the input, however v1 api of cryptsy is deprecated officially and why I havent taken care of this. Check out v2 api of cryptsy.

**Comment by fogodlc** [comment]
Thanks. Found it later that night. I appreciate your sharing the code and giving me a chance to springboard into coding some python for my first time. I have some experience in other languages. Thanks again.
